Solved email notification pipeline issue

diff --git a/.github/workflows/maven1.yml b/.github/workflows/maven1.yml
--- a/.github/workflows/maven1.yml
+++ b/.github/workflows/maven1.yml
@@ -75,25 +75,25 @@ jobs:
 
 
     # Start Docker Compose services if not running
-      - name: Send Email Notification
-        if: success() || failure()
-        env:
-          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
-          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
-          RECIPIENTS: "chirag.ali47@gmail.com"
-        run: |
-          echo "Subject: Test Automation Completed" > email.txt
-          echo "To: $RECIPIENTS" >> email.txt
-          echo "From: $SMTP_EMAIL" >> email.txt
-          echo "Hello Stakeholders," >> email.txt
-          echo "" >> email.txt
-          echo "The automated tests have completed." >> email.txt
-          echo "You can view the test results at the following link:" >> email.txt
-          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> email.txt
-          echo "" >> email.txt
-          echo "Best regards," >> email.txt
-          echo "Your Automation Team" >> email.txt
-          cat email.txt | ssmtp -t
-
-      - name: Cleanup
-        run: rm email.txt
+#      - name: Send Email Notification
+#        if: success() || failure()
+#        env:
+#          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
+#          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
+#          RECIPIENTS: "chirag.ali47@gmail.com"
+#        run: |
+#          echo "Subject: Test Automation Completed" > email.txt
+#          echo "To: $RECIPIENTS" >> email.txt
+#          echo "From: $SMTP_EMAIL" >> email.txt
+#          echo "Hello Stakeholders," >> email.txt
+#          echo "" >> email.txt
+#          echo "The automated tests have completed." >> email.txt
+#          echo "You can view the test results at the following link:" >> email.txt
+#          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> email.txt
+#          echo "" >> email.txt
+#          echo "Best regards," >> email.txt
+#          echo "Your Automation Team" >> email.txt
+#          cat email.txt | ssmtp -t
+#
+#      - name: Cleanup
+#        run: rm email.txt
